### PR TITLE
[BREAKING] Delete in-viewport mixin

### PR DESCRIPTION
**Pull request by SergeAstapov**
@snewcomer @cibernox FYI I'm still working on removal of in-viewport mixin which was slated for v4.0

### CODE REVIEW

**Comment by SergeAstapov** [comment]
@snewcomer @cibernox this is now ready for your review and targets a next major release as it's breaking change (planned for v4 but the release was cut before we finished this).

Bug thanks to @sergeykers and @andrei-sviazhin for they help!

**Review by snewcomer — APPROVED** [review]
Beautiful and thank you.  We can do a patch bump bc we had a deprecation so users should expect it to work now.

**Comment by SergeAstapov** [comment]
@snewcomer yeah, sounds like a plan! mind to merge and release if all looks good?

**Comment by snewcomer** [comment]
I'll let @cibernox merge when he was a moment!

**Comment by SergeAstapov** [comment]
@cibernox just a friendly ping on this PR

**Comment by cibernox** [comment]
Merged! I suppose I should release 5.0 now tho. No big deal, numbers are cheap.

**Comment by SergeAstapov** [comment]
@cibernox yes, please do v5! So we follow semver and not troll users of this addon

**Pull request merged**
