### PR TITLE
Fix for items larger than viewport

### PR DESCRIPTION
**Pull request by rhengeveld**
For each axis (X,Y) the item is considered in the viewport when:  
- It's dimensions are fully within the viewport (original calculation)
- It's dimension are fully outside the viewport (new)

So the behaviour only changes for items that are actually taller/wider :)

This probably also fixes https://github.com/DockYard/ember-in-viewport/issues/37

### CODE REVIEW

**Comment by rhengeveld** [comment]
Sadly I don't know much about automated testing yet @ Javascript, so I don't know what's with the Travis CI build failing :disappointed:

**Comment by awaer** [comment]
@rhengeveld The travisCI failure doesn't appear to be related to your PR. It looks like a recent update to the `ember-suave` addon (#59) is now causing a JSCS linter error.

```sh
not ok 10 Chrome 49.0 - JSCS - helpers: helpers/module-for-acceptance.js should pass jscs
    ---
        actual: >
            false
        expected: >
            true
        stack: >
                at http://localhost:7357/assets/test-support.js:4039:12
                at Object.<anonymous> (http://localhost:7357/assets/tests.js:127:5)
                at runTest (http://localhost:7357/assets/test-support.js:2688:28)
                at Object.Test.run (http://localhost:7357/assets/test-support.js:2673:4)
                at http://localhost:7357/assets/test-support.js:2815:11
                at process (http://localhost:7357/assets/test-support.js:2474:24)
        message: >
            helpers/module-for-acceptance.js should pass jscs.
            requireSpread: Illegal use of apply method. Use the spread operator instead at helpers/module-for-acceptance.js :
                 9 |
                10 |      if (options.beforeEach) {
                11 |        options.beforeEach.apply(this, arguments);
            -----------------------------------^
                12 |      }
                13 |    },
            requireSpread: Illegal use of apply method. Use the spread operator instead at helpers/module-for-acceptance.js :
                17 |
                18 |      if (options.afterEach) {
                19 |        options.afterEach.apply(this, arguments);
            ----------------------------------^
                20 |      }
                21 |    }
```

**Comment by poteto** [comment]
@rhengeveld Thanks for this PR! If you rebase against the latest master, your build should stop breaking.

**Comment by rhengeveld** [comment]
@poteto Thanks for the heads up, this seems to do the trick! 😄

**Comment by markmhx** [comment]
It'd be great to have this PR merged. I'm also dealing with this problem of elements taller than the viewport not triggering hooks.

**Comment by jasonmit** [comment]
Something to consider, if not already considered, `window.innerWidth` and `window.innerHeight` can trigger a reflow.

**Comment by snewcomer** [comment]
If using the latest releases of this addon, `IntersectionObserver` will always trigger once and check `didEnterViewport`.  Closing for now, but feel free to open again if need be!

**Pull request closed without merging**
