### PR TITLE
Guard against `viewportListeners` being undefined

### LINKED ISSUE #45: Error in _unbindListeners in component integration tests
After mixing this into a component, integration tests keep throwing `Uncaught TypeError: Cannot read property 'forEach' of undefined`. This is on Ember 2.2.

It's failing when it's finding that `viewportListeners` hasn't been set. 

Is there something I need to do to my test to get this to work like it should? Otherwise, what's the best way to test a component with this mixed in?

### PR DESCRIPTION
**Pull request by elidupuis**
Closes #45.

Note that I ran into the jQuery version conflict that appeared with the recent jQuery release. Pinning `jquery` in `bower.json` solves this `"jquery": "1.11.3"`. I didn't include this in the PR since it's unrelated.

### CODE REVIEW

**Comment by elidupuis** [comment]
Test failing because to `jquery` version issue as mentioned above: https://travis-ci.org/dockyard/ember-in-viewport/jobs/104706129#L2060

**Comment by poteto** [comment]
@elidupuis If you rebase against master, and change your PR target we should be all set!

**Comment by elidupuis** [comment]
@poteto Is there actually a way to change the target of a PR or do you just mean open a new one?

**Comment by elidupuis** [comment]
Came across this and had a good chuckle :joy: https://github.com/isaacs/github/issues/18

Opened a new PR to `master`: #60.

**Comment by poteto** [comment]
Closed by #60

**Pull request closed without merging**
