### PR TITLE
use one rAF manager

### PR DESCRIPTION
**Pull request by snewcomer**
Huge thanks to the work done in #103 

Also splits out the  recursive rAF function to it's own service.

close #103

### CODE REVIEW

**Comment by snewcomer** [comment]
@jheth Hey Joe 👋 Would you mind trying out this branch?  This uses an rAFPoolManager to use one rAF for all your components on the page.  Also, I realized we use a concept called `viewportSpy`.  By default it is `false` (may change the default in the future).  But `viewportSpy` - 

```When false, the Mixin will only watch the Component until it enters the viewport once```

So if you had `viewportSpy` set to `true`, that is why you were seeing it continuously fire.

**Comment by jheth** [comment]
@snewcomer  The branch is much improved over the previous where I was seeing rAF for each LazyImage component I had on the page.  However, I'm not seeing the rAF ever stop even after all images are loaded.

This is a performance chart on page load with 10 lazy image components on the page.
screen shot 2018-05-01 at 6 29 12 pm

This is a close up, showing a single rAF is being used, which is much better than before.
screen shot 2018-05-01 at 6 30 37 pm

This is a performance chart after scrolling to the bottom of the page and all images had been scrolled into the viewport. I don't see a difference from the first chart. I would have expected no more rAF requests.

screen shot 2018-05-01 at 6 35 30 pm

**Comment by snewcomer** [comment]
@jheth Do you have viewportSpy set to true (ensures continuous rAF calls, default is false)?  Here, we are trying to set `_stopListening` to true.

[Here](https://github.com/DockYard/ember-in-viewport/blob/34f383d2304b2fbd698983f7aa1c5328d9ae0198/addon/mixins/in-viewport.js#L266) and [here](https://github.com/DockYard/ember-in-viewport/blob/34f383d2304b2fbd698983f7aa1c5328d9ae0198/addon/mixins/in-viewport.js#L327).

Let me know what you have set for this property.

**Comment by jheth** [comment]
I do not have `viewportSpy` enabled, it's using the default of false.

**Comment by snewcomer** [comment]
@jheth I added a test with one slightly small regression.  Lmk if you see anything different.  Otherwise, perhaps simplify things by putting one image on the page and put a debugger [here](https://github.com/DockYard/ember-in-viewport/blob/0c605ee1994f13725a28aa7d9856590d25809416/addon/mixins/in-viewport.js#L179) and ensure `_stopListening` is true.

**Comment by snewcomer** [comment]
@jheth Also you can test this behavior of turning off rAF in the dummy app on the rAF route.  I'll merge as is if you don't mind and we can make further improvements in the future. 

Thanks again for everything here.

**Pull request merged**
