### PR TITLE
Fix Demo Page

### LINKED ISSUE #68: Rehost demo app
The demo app is no longer available since divshot went offline.

> **Site Unavailable**
> 
> Divshot, the hosting provider for this website, has ceased operation as of December 22, 2015 ... If this is your website, please update your DNS to point to a new hosting provider!

http://development.ember-in-viewport-demo.divshot.io/

### LINKED ISSUE #71: Demo Website is Down
http://development.ember-in-viewport-demo.divshot.io/ shows this:

### PR DESCRIPTION
**Pull request by blimmer**
This PR fixes the demo app that has been down since DivShot went away.

It does the following:
- Migrates the demo app from [a separate repo](https://github.com/poteto/ember-in-viewport-demo) into this repo's dummy app.
- Maintains the one existing test
- Upgrades Ember CLI to latest version
- Uses [ember-cli-github-pages](https://github.com/poetic/ember-cli-github-pages) for the demo app ([example](https://blimmer.github.io/ember-in-viewport/))

Remaining for collaborators ( @poteto @bcardarella ) to make this work:
- [ ] Grab my gh-pages branch https://github.com/blimmer/ember-in-viewport/tree/gh-pages or follow the instructions [here](https://github.com/poetic/ember-cli-github-pages#installation--setup) to generate a gh-pages branch. Since it has an entirely different history, I can't figure out how to make a PR for it.
- [ ] Delete the [old demo app repo](https://github.com/poteto/ember-in-viewport-demo)
- [ ] Update the repo description (has old divshot link to demo)
- [ ] Update any references to the old demo app URL (blog posts, etc)

Fixes:
https://github.com/poteto/ember-in-viewport-demo/issues/1
Fixes #71 
Fixes #68

### CODE REVIEW

**Comment by blimmer** [comment]
@poteto Is there value in me fixing this PR? It looks like in #75 you upgraded ember-cli, which caused conflicts here.

**Comment by poteto** [comment]
Yes please!

**Comment by blimmer** [comment]
@poteto this is rebased and ready to go!

**Comment by blimmer** [comment]
@poteto is this worth rebasing again? Or should I close it?

**Comment by martndemus** [comment]
@poteto Should I rebase and merge this for you?

**Comment by poteto** [comment]
Sounds good

**Comment by martndemus** [comment]
Hmm, the test added in #82 is blocking this from being merged. @blimmer Could you try and migrate that test into an integration test? Then we would be good to merge!

**Comment by martndemus** [comment]
Maybe @kellyselden could give it a shot?

**Comment by blimmer** [comment]
I won't be able to look into this until this weekend at the earliest.

**Comment by snewcomer** [comment]
Closing this for now.  Sry this never made it in 🙏.  If anybody needs some examples or test examples, they are in the dummy app.

**Pull request closed without merging**
