### PR TITLE
use this.get pattern to avoid forEach = _ember["default"].EnumerableUtils.forEach.

### PR DESCRIPTION
**Pull request by systembugtj**
use this.get, instead of get(this...), so don't need to have lodash involved.

### CODE REVIEW

**Comment by poteto** [comment]
I don't get the goal of this PR. [`forEach`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach) is a part of ES5, and is supported by almost all modern browsers. The deprecated `EnumerableUtils` is not being used here.

**Comment by bcardarella** [comment]
I modified the title of this PR. It felt too passive aggressive.

**Comment by systembugtj** [comment]
Yes, forEach is fine in ES5. But the major issue is the pattern in current code when works with emberjs 2.x, it will have below line

var forEach = _ember["default"].EnumerableUtils.forEach be generated. But in 2.x it doesn't have forEach anymore, which cause exceptions.

BTW: why use get(this, ..) not this.get(...)?

**Comment by systembugtj** [comment]
@bcardarella thanks for fixing the title. Sorry about that. :+1:

**Comment by systembugtj** [comment]
More clear, the EnumerableUtils is removed at 2.x

http://emberjs.com/blog/2015/05/24/another-two-oh-status-update.html

The ArrayPolyfills and EnumerableUtils libraries are being pulled out into a library; most apps should prefer lodash or other utility libs.

**Comment by rwjblue** [comment]
@systembugtj - This library is not using EnumerableUtils or ArrayPolyfills. I believe I linked to the PR that fixed this in the issue you created.

**Comment by systembugtj** [comment]
Thanks. Looks like this is caused by ember-lazy-image, the default package downloaded from npm still refer to 1.2.5 of this lib.

**Comment by systembugtj** [comment]
@rwjblue thanks for the clarification. The issue is not from this lib. But ember-lazy-image.

**Pull request closed without merging**
