### PR TITLE
Remove Ember.on listeners

### PR DESCRIPTION
**Pull request by poteto**

### CODE REVIEW

**Comment by rwjblue** [comment]
:+1:

**Comment by kanongil** [comment]
This broke in my ember 1.12.1 app, upgrading from 2.0.0 to 2.0.1.

**Comment by poteto** [comment]
Do you have a stack trace?

**Comment by kanongil** [comment]
Sorry, don't have time to look further into it right now. I have only observed that my app looks as normal with 2.0.1 but seems to never triggers the `didEnterViewport` hook that we use.

I have fixed it locally by reverting to 2.0.0.

**Comment by poteto** [comment]
Okay, thanks for reporting. I'll have a look and see if I can figure it out, do let us know if you manage to isolate the cause

**Pull request merged**
